### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ozdemircili** [uncommitted-and-forgotten/django-uptimerobot#1]
Hi,

Im getting the following error:

ImproperlyConfigured at /uptimerobot
The included urlconf <module 'uptimerobot.urls' from '/home/action/envs/django-sample.app/local/lib/python2.7/site-packages/django_uptimerobot-0.0.6-py2.7.egg/uptimerobot/urls.py'> doesn't have any patterns in it
Request Method: GET
Request URL:    http://coder-39433.euw1.actionbox.io:8000/uptimerobot
Django Version: 1.5.1
Exception Type: ImproperlyConfigured
Exception Value:  
The included urlconf <module 'uptimerobot.urls' from '/home/action/envs/django-sample.app/local/lib/python2.7/site-packages/django_uptimerobot-0.0.6-py2.7.egg/uptimerobot/urls.py'> doesn't have any patterns in it
Exception Location: /home/action/envs/django-sample.app/local/lib/python2.7/site-packages/django/core/urlresolvers.py in url_patterns, line 351
Python Executable:  /home/action/envs/django-sample.app/bin/python
Python Version: 2.7.3
Python Path:  
['/home/action/github/django-sample-app',
 '/home/action/github/django-sample-app/sampleapp',
 '/home/action/envs/django-sample.app/local/lib/python2.7/site-packages/readline-6.2.4.1-py2.7-linux-x86_64.egg',
 '/home/action/envs/django-sample.app/local/lib/python2.7/site-packages/django_uptimerobot-0.0.6-py2.7.egg',
 '/home/action/envs/django-sample.app/lib/python2.7',
 '/home/action/envs/django-sample.app/lib/python2.7/plat-linux2',
 '/home/action/envs/django-sample.app/lib/python2.7/lib-tk',
 '/home/action/envs/django-sample.app/lib/python2.7/lib-old',
 '/home/action/envs/django-sample.app/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/action/envs/django-sample.app/local/lib/python2.7/site-packages']
Server time:    Thu, 24 Oct 2013 15:06:57 +0000

What would be the problem?

**Comment by philippeowagner** [comment]
Hello @ozdemircili 
Thanks for opening an issue. Everything should work now. The main benefit of this app is described in this section https://github.com/arteria/django-uptimerobot#usage - the rest is more or less "Django" related infrastructure at the moment.

**Comment by ozdemircili** [comment]
Thank you Philip!
